# Generated by Django 2.1.5 on 2019-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rea_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('instructor', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='choreographer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='production',
            name='director',
            field=models.CharField(default=True, max_length=120),
        ),
        migrations.AddField(
            model_name='production',
            name='musical_director',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
