# Generated by Django 2.1.5 on 2019-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rea_app', '0002_auto_20190221_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='photo_url',
            field=models.TextField(default=True),
        ),
    ]
